### ISSUE TITLE
CardReaderEmulator.ino

### ISSUE THREAD

**Issue by DimaMukhin84** [avkw1/ArduinoCardReaderEmulator#1]
Good afternoon.
Where can I get pins_arduino.h for the sketch to work?

**Comment by avkw1** [comment]
This file provided by Arduino IDE.
"pins_arduino.h is a board-specific file and if the compiler can't find it this could be because the board type hasn't been defined correctly. The boards.txt entry should include a build.variant property that names a directory under arduino/variants that contains the corresponding pins_arduino.h." [https://forum.arduino.cc/t/error-pins_arduino-h-no-such-file-or-directory/216441](https://forum.arduino.cc/t/error-pins_arduino-h-no-such-file-or-directory/216441)
